/* 
Data......: 03/08/2025
Autor.....: Datalib Tecnologia e Treinamento em Dados
Título....: MSSQL 050 - Bug no SQL Server 2025.sql
Copyright.: Utilizacao somente para fins educacionais e didaticos com autorizacao do autor.
Referencia: 
Comentario: Bug encontrado no SQL Server 2025 vesão Preview
*/
 

CREATE DATABASE BUGSQL2025
GO

USE BUGSQL2025
GO

CREATE TABLE CLIENTE (
	CLIENTEID	INT NOT NULL PRIMARY KEY,
	NOME		VARCHAR(30),
	CIDADE		VARCHAR(20),
	UF			CHAR(02)
)
GO

CREATE TABLE VENDEDOR (
	VENDEDORID	INT NOT NULL PRIMARY KEY,
	NOME		VARCHAR(30)
)
GO

CREATE TABLE PEDIDO (
	PEDIDOID	INT NOT NULL PRIMARY KEY,
	DATA_PED	DATE,
	CLIENTEID	INT NOT NULL,
	VENDEDORID	INT NOT NULL,
	CONSTRAINT	FK_PEDIDO_CLIENTEID FOREIGN KEY(CLIENTEID) REFERENCES CLIENTE(CLIENTEID),
	CONSTRAINT  FK_PEDIDO_VENDEDORID FOREIGN KEY(VENDEDORID) REFERENCES VENDEDOR(VENDEDORID)
)
GO

--MONTAR OP DIAGRAMA


--FAZER ALGUMA ALTERACAO NAS TABELAS DO DIAGRAMA
CREATE TABLE PRODUTO (
	PRODUTOID		INT NOT NULL PRIMARY KEY,
	DESCRICAO_PROD	VARCHAR(30),
	UNIDADE			CHAR(02),
	PRECO			DECIMAL(10,2)
)
GO


CREATE TABLE ITEM_PEDIDO (
	PEDIDOID		INT NOT NULL,
	ITEMPEDIDOID	INT NOT NULL,
	PRODUTOID		INT,
	QUANTIDADE		INT,
	PRECO			DECIMAL(10,2),
	TOTAL			AS QUANTIDADE * PRECO,
	CONSTRAINT PK_ITEM_PEDIDO PRIMARY KEY(PEDIDOID, ITEMPEDIDOID),
	CONSTRAINT FK_ITEM_PEDIDO_PEDIDOID FOREIGN KEY(PEDIDOID) REFERENCES PEDIDO(PEDIDOID),
	CONSTRAINT FK_ITEM_PEDIDO_PRODUTOID FOREIGN KEY(PRODUTOID) REFERENCES PRODUTO(PRODUTOID)
)
GO

--MOSTRAR A ATUALIZACAO DO DIAGRAMA COM O ADD TABLE

--MOSTRAR A ATUALIZACAO DELETANDO O DIAGRAMA

--MOSTRAR A ATUALIZACAO DELETANDO A BASE DE DADOS



/*
   Ficou com alguma dúvida?
   Comentem! Responderemos o quanto antes a sua dúvida!

   Gostou dessa dica ou vídeo?
   Compartilhe, curta e assine o nosso canal!
  
   Siga as nossas redes sociais em:
   Youtube:    youtube.com/@datalib22
   X:          x.com/datalib_tec 
   Instagram:  instagram.com/datalib_tec 
   Blog:       www.datalib.com.br
   Github:     https://github.com/datalibtec
*/